Add Interpolation capabilities to OTD
InfinityGhost/OpenTabletDriver pull request #302
Opened 2020-09-17 21:30 UTC by X9VoiD

# Changes
- [x] Added interpolation interface
- [x] Added noop interpolator
- [x] Declare ITabletReport Position and Pressure setter
- [x] UX Side controls

# Issues
- [ ] Interpolator doesn't stop after pen leaves tablet range
- [ ] Plugin attributes is not applied to IInterpolator instances

2020-09-21 20:44 UTC, InfinityGhost requested changes

2020-09-21 20:44 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/IOutputMode.cs
> +        void Read(ITabletReport report);
Do NOT do this, this only creates problems.

2020-09-21 20:44 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/IOutputMode.cs
> +        void Read(ITabletReport report);
We rely on all report types being passed to the output mode, and in the read function itself will cast to ITabletReport if needed.

2020-09-21 20:47 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Output/IOutputMode.cs
> +        void Read(ITabletReport report);
So we cast it back to IDeviceReport after modifying the ITabletReport in the interpolator?

2020-09-21 21:20 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Output/IOutputMode.cs
> +        void Read(ITabletReport report);
Reverted IOutputMode's Read back to IDeviceReport. Tested working on G640S normal and aux report

2020-09-22 01:35 UTC, X9VoiD commented
Helps with #303

2020-09-23 01:44 UTC, X9VoiD commented
Will rework this again, there are issues found after fiddling with it.

## Issues
* Pen Arrive/Left spams for a while when pen arrives then settles down
* InterpolationEngine rarely gets stuck on Pen Arrive/Left events
* InterpolatorArgs is unclear with its intents
    * TimeDelta have different meaning depending on where it's called (will probably just leave this to the plugin)
    * Position/Pressure on Interpolate is the same on NewReport (Interpolate's Position/Pressure args should provide current interpolation's position)

2020-09-23 01:48 UTC, InfinityGhost commented
I really think this PR should take a different direction, more towards giving up the interfaces to implement their own interpolator instead of writing one directly to just be used. I think filters should be the ones implementing the interpolator interface.

2020-09-23 02:43 UTC, X9VoiD commented
The `InterpolationEngine` currently only provides these additional functions

* Create fake reports every specified Hz, to be modified by implementers of abstract class `Interpolator` ([InterpolationEngine.cs#L44](https://github.com/InfinityGhost/OpenTabletDriver/blob/a1edc2b3808fb63ffec56013943fefebef71feaa/OpenTabletDriver.Plugin/Tablet/Interpolator/InterpolationEngine.cs#L44))
* Dynamically switch interpolation on and off when pen arrives/leaves (fixes problems with cursor getting stuck due to interpolator still sending fake reports)
    * This function needs a calculated report rate to work properly, hence the `DriverState.ReportRate`

So rest assured the interpolation actually only happens on the active `Interpolator` plugin

2020-09-24 03:41 UTC, X9VoiD commented
New changes pushed

### Changes
* Lose `DriverState.ReportRate` for simplicity
* Make it clear that `NewReport()` args are read-only
* Make it clear that `Interpolate()` args are write-only
* Fixed rare cases where OTD gets stucked in PenLeft event
* Fixed PenArrived/PenLeft spamming

There are essentially no issues anymore with the PR (except slightly higher cpu usage due to busy wait). Both hawku smoothing's and devocub antichatter's interpolation can be implemented with the abstract class Interpolation as a dll plugin

2020-09-26 21:59 UTC, InfinityGhost requested changes

2020-09-26 22:00 UTC, InfinityGhost commented
Resolve merge conflicts after #322 and #288

2020-09-27 00:38 UTC, X9VoiD commented
Merge conflicts resolved and formatting issues fixed

2020-09-27 02:23 UTC, InfinityGhost requested changes
Okay that's a full review now.

2020-09-27 02:23 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Micro/MicroStopwatch.cs
> +                );
I'm sorry lmfao
```cs
throw new PlatformNotSupportedException(
    "On this system the high-resolution " +
    "performance counter is not available"
);
```

2020-09-27 02:23 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Micro/MicroTimer.cs
> +                               ref bool stopTimer)
```cs
void NotificationTimer(
    ref long timerIntervalInMicroSec,
    ref long ignoreEventIfLateBy,
    ref bool stopTimer
)
{
    // stuff
```

2020-09-27 02:23 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Micro/MicroTimer.cs
> +        public event MicroTimerElapsedEventHandler MicroTimerElapsed;
This will suffice. 
```cs
public event EventHandler<MicroTimerEventArgs> MicroTimerElapsed;
```

2020-09-27 02:23 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Micro/MicroTimerEventArgs.cs
> +namespace OpenTabletDriver.Plugin.Micro
Reason for the naming of the namespace? I think `OpenTabletDriver.Plugin.Timers` or something similar makes more sense.

2020-09-27 02:23 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/ITabletReport.cs
> +        uint Pressure { get; set; }
What's the need for this change? I personally think a new report should be created for each new report instead of modifying an existing one.

2020-09-27 02:23 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +                InterpolationEngine.HandleReport(report);
Not sure how I feel about this change, maybe that function in `InterpolationEngine` should be in `Driver`?

2020-09-27 02:47 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Micro/MicroStopwatch.cs
> +                );
lmao

2020-09-27 02:49 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Micro/MicroTimerEventArgs.cs
> +namespace OpenTabletDriver.Plugin.Micro
The code from that namespace is from [MicroLib](https://www.codeproject.com/Articles/98346/Microsecond-and-Millisecond-NET-Timer) so the name came from there

2020-09-27 02:50 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/ITabletReport.cs
> +        uint Pressure { get; set; }
At the time i didn't know we could make ITabletReports by making a dummy like you did before. Will make the change

2020-09-27 02:55 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/ITabletReport.cs
> +        uint Pressure { get; set; }
I would suggest calling it something like `InterpolatedTabletReport`

2020-09-27 02:57 UTC, X9VoiD commented on OpenTabletDriver/Driver.cs
> +                InterpolationEngine.HandleReport(report);
We can move InterpolationEngine.HandleReport to Driver but that HandleReport needs locking, StateLock, so there won't be race conditions when HandleReport and Interpolate fires at the same time. I wanted to keep references to StateLock to only inside the InterpolationEngine itself

2020-09-27 03:02 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Micro/MicroTimerEventArgs.cs
> +namespace OpenTabletDriver.Plugin.Micro
Will rename to `OpenTabletDriver.Plugin.Timers`

2020-09-27 03:05 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +                InterpolationEngine.HandleReport(report);
Maybe the functions in `InterpolationEngine` should be in `Driver` then? I'm not too keen on the use of the DriverState class inside of the driver itself when the driver itself is already available.

2020-09-27 03:17 UTC, X9VoiD commented on OpenTabletDriver/Driver.cs
> +                InterpolationEngine.HandleReport(report);
Oh uhh, my bad, I don't think the HandleReport could be moved. I forgot that the reason the `InterpolationEngine` is there is so we could use PenInRange's `internal set` and properly invoke PenArrive event. The PenInRange's `set` is not available from driver. And PenArrive, PenInRange is in DriverState so plugins could use it, or future output modes that can make use of "pen left" events. If you could think of a way to move stuff around though then I'll comply, double HandleReport looks bad I agree

2020-10-11 05:14 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                if (((DateTime.UtcNow - this.lastTime).TotalMilliseconds < this.reportMsAvg * 1.5) && this.inRange)
We could maybe make this non-linear so that it would work across virtually any report rate

2020-10-11 06:24 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                if (((DateTime.UtcNow - this.lastTime).TotalMilliseconds < this.reportMsAvg * 1.5) && this.inRange)
How non-linear tho?

When reportMsAvg is 7.5ms, interpolation will stop when last report is 11.25ms
When reportMsAvg is 3.75ms, interpolation will stop when last report is 5.625ms

So in a sense this is linear yes but it'll work for most report rates (but not when reaching 500hz+ i guess). If you're thinking of another formula tho lmk, will plug that here instead

2020-10-11 06:47 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                if (((DateTime.UtcNow - this.lastTime).TotalMilliseconds < this.reportMsAvg * 1.5) && this.inRange)
Exactly where this can become flimsy, we do need support for as many report rates as possible to avoid any future problems. Will think on some possible formulas to go off of, but I'm thinking either quadratic or root

2020-10-16 20:35 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                if (((DateTime.UtcNow - this.lastTime).TotalMilliseconds < this.reportMsAvg * 1.5) && this.inRange)
How about making it still linear but instead, we will scale according to these:

| Delta | Timeout |
| :--: | :--: |
| 1ms | 3ms |
| 7.5ms | 11.25ms |

So basically, when average delta is 1ms, timeout is 3ms, then that will scale linearly to 7.5ms : 11.25ms. We will clamp timeout to 3ms when report rate is lower than 1ms

2020-10-16 23:39 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                if (((DateTime.UtcNow - this.lastTime).TotalMilliseconds < this.reportMsAvg * 1.5) && this.inRange)
Reasonable, lets do that then.

2020-10-17 11:06 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                if (((DateTime.UtcNow - this.lastTime).TotalMilliseconds < this.reportMsAvg * 1.5) && this.inRange)
Change pushed.

For this functionality, I used Vector2 functions to basically form a line. X is the base reportMs and Y is the limit.

2020-11-18 20:25 UTC, InfinityGhost commented
Revert the MacOS accelerated code and I'll go ahead and merge. We'll just add it in a later PR prior to release.

2020-11-19 02:48 UTC, X9VoiD commented
Reverted :bread:

2020-11-19 16:39 UTC, InfinityGhost requested changes

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Native/Linux/Timers/Enum.cs
> +    }
Separate into 3 files

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Native/Linux/Timers/Structs/SigEvent.cs
> +    }
Move into separate files

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Native/Linux/Timers/Structs/TimerSpec.cs
> +    }
Move into separate files

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Native/Linux/Timers/Structs/SigEvent.cs
> +    public delegate void TimerCallback(SigVal a);
Move to `OpenTabletDriver.Native/Linux/Timers/Timers.cs`

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Native/OSX/OSX.cs
> +
Unused changes?

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/IDriver.cs
> +        event Action<IDeviceReport> ReportRecieved;
Invalid change, only `EventHander<T>` is supported in StreamJsonRpc

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/ITimer.cs
> +        public event Action Elapsed;
`public` is unnecessary on interfaces.

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver/DeviceReader.cs
> +        public virtual event Action<T> Report;
Keep `EventHandler<T>`, the `sender` parameter can prove to be useful in the future.

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver/Interop/Timer/LinuxTimer.cs
> +        }
Make this change
```diff
diff --git a/OpenTabletDriver/Interop/Timer/LinuxTimer.cs b/OpenTabletDriver/Interop/Timer/LinuxTimer.cs
index 6790d54..764c026 100644
--- a/OpenTabletDriver/Interop/Timer/LinuxTimer.cs
+++ b/OpenTabletDriver/Interop/Timer/LinuxTimer.cs
@@ -46,7 +46,7 @@ namespace OpenTabletDriver.Interop.Timer
                     Log.Write("LinuxTimer", $"Failed creating timer: {(ERRNO)Marshal.GetLastWin32Error()}", LogLevel.Error);
                 }
 
-                var interval = Interval * 1000 * 1000;
+                double interval = Interval * 1000 * 1000;
 
                 timeSpec = new TimerSpec
                 {
@@ -121,14 +121,7 @@ namespace OpenTabletDriver.Interop.Timer
 
         public bool Enabled { private set; get; }
 
-        private double _interval;
-        public float Interval {
-            set
-            {
-                _interval = value;
-            }
-            get => (float)_interval;
-        }
+        public float Interval { set; get; }
 
         public event Action Elapsed;
     }
```

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver/Interop/Timer/WindowsTimer.cs
> +                timeGetDevCaps(ref caps, (uint)Marshal.SizeOf(caps));
Why not `sizeof(TimeCaps)`?

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver/Interop/Timer/WindowsTimer.cs
> +        }
Why is there a function like this? If its not implemented here why is it implemented anywhere else?

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Limiter.cs
> +        private static readonly Vector2 maximum = new Vector2(7.5f, 7.5f * 1.5f);
Why are these constantly defined? Just wondering the logic behind it.

2020-11-19 16:39 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        }
`ITimer` implements `IDisposable`, dispose here.

2020-11-19 17:24 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Limiter.cs
> +        private static readonly Vector2 maximum = new Vector2(7.5f, 7.5f * 1.5f);
[Link to previous discussion](https://github.com/InfinityGhost/OpenTabletDriver/pull/302#discussion_r506708728)

2020-11-19 17:34 UTC, X9VoiD commented
Requested changes pushed :bread:

2020-11-23 04:28 UTC, InfinityGhost approved these changes

2020-11-24 03:56 UTC, merged