Fix ProductID and ReportID of New 1060 Plus
InfinityGhost/OpenTabletDriver pull request #318
Opened 2020-09-26 07:53 UTC by X9VoiD

2020-09-26 14:47 UTC, InfinityGhost commented
Lets make sure that other users of the New 1060 Plus don't have this same situation.

2020-09-28 19:03 UTC, InfinityGhost requested changes

2020-09-28 19:03 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Huion/New 1060 Plus.json
> +    "ProductID": 110,
How about we make this change for the alternate digitizer?

2020-10-05 00:14 UTC, InfinityGhost commented
#350 might be related to this

2020-10-05 07:45 UTC, X9VoiD commented
The diagnostics from #350 confirmed that the product id is correct, but the input report length is different.
We could make an alternate identifier, one for InputReportLength 8 and one for InputReportLength 12

2020-10-05 07:48 UTC, X9VoiD commented
Oh... uhh. We can't make an alternate identifier for MaxPressure lol. We should really rework the TabletProperties now

2020-10-12 04:17 UTC, InfinityGhost commented
Update this to conform to latest tablet configuration changes

2020-10-14 16:16 UTC, X9VoiD commented
PR updated to new config format

2020-10-14 16:23 UTC, InfinityGhost commented
#350, what should we do about it?

2020-10-14 16:32 UTC, X9VoiD commented
Converted the PR to draft since we can't test the configurations on Windows (device stream seems to not open), and not verified yet.

2020-12-16 23:20 UTC, closed without merging

2020-12-16 23:21 UTC, X9VoiD commented
Superseded by #562