Add ReportRate in TabletDebugger's TabletReport
InfinityGhost/OpenTabletDriver pull request #319
Opened 2020-09-26 07:58 UTC by X9VoiD

# Changes
* Use [cumulative moving average](https://en.wikipedia.org/wiki/Moving_average) to calculate average report rate

2020-09-26 14:45 UTC, InfinityGhost requested changes

2020-09-26 14:45 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/TabletDebugger.cs
> +        private DateTime lastTime;
```cs
lastTime = DateTime.UtcNow;
```
Instead of having the initialization in the ctor

2020-09-26 14:45 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/TabletDebugger.cs
> +                        + $"\nReportRate:{(uint)(1000 / reportRate)}hz";
Replace `\n` with `Environment.NewLine`

2020-09-26 23:11 UTC, X9VoiD commented
Requested changes pushed

2020-09-29 14:08 UTC, InfinityGhost approved these changes

2020-09-29 15:22 UTC, merged