Fallback to Application Directory for Configuration
InfinityGhost/OpenTabletDriver pull request #365
Opened 2020-10-13 16:09 UTC by X9VoiD

# Changes
- Check first if the user-supplied configuration directory is existing.
- Then check if there is a configuration folder in current working directory.
- And finally fallback to directory of OTD daemon to search for the configuration folder when above checks failed.

# Issues
- Fixes #357

# Reproduction
- ## Windows
  - Use File Explorer search function to launch daemon. (will set cwd to `C:\Windows\System32`)
- ## Linux
  - Launch OTD daemon directly without being in its directory.
- ## All Platforms
  - Supply non-existent configuration directory to daemon.

2020-10-16 03:39 UTC, InfinityGhost requested changes

2020-10-16 03:39 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/Program.cs
> +                    }
We should put this directly in AppInfo

2020-10-17 21:29 UTC, X9VoiD commented on OpenTabletDriver.Daemon/Program.cs
> +                    }
Change pushed

2020-10-18 00:16 UTC, InfinityGhost requested changes

2020-10-18 00:16 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/Program.cs
> +using System.Reflection;
Remove unused namespace reference

2020-10-18 10:19 UTC, X9VoiD commented on OpenTabletDriver.Daemon/Program.cs
> +using System.Reflection;
Change pushed

2020-10-18 17:00 UTC, InfinityGhost approved these changes

2020-10-18 17:00 UTC, merged