Provide access to VirtualScreen for plugins
InfinityGhost/OpenTabletDriver pull request #366
Opened 2020-10-13 16:42 UTC by X9VoiD

This helps with VMulti-based plugins which needs to normalize values to VirtualScreen size

2020-10-13 16:43 UTC, skyborgff commented
Great, this is better than having to create a "fake" AbsoluteOutputMode just to get that info

2020-10-13 16:55 UTC, InfinityGhost requested changes

2020-10-13 16:55 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +        public IVirtualScreen VirtualScreen { get; } = Interop.Platform.VirtualScreen;
The current state of this code will only set the virtual screen one time at construction. While this is sufficient now, we might support display size updates in the future.
```cs
public IVirtualScreen VirtualScreen => Interop.Platform.VirtualScreen;
```

2020-10-13 17:00 UTC, X9VoiD commented on OpenTabletDriver/Driver.cs
> +        public IVirtualScreen VirtualScreen { get; } = Interop.Platform.VirtualScreen;
Change pushed

2020-10-14 04:16 UTC, InfinityGhost approved these changes

2020-10-14 15:56 UTC, merged