Fixed crash when trying to load plugins
InfinityGhost/OpenTabletDriver pull request #378
Opened 2020-10-14 22:36 UTC by skyborgff

Example:
If the dlls from this file are in the plugins folder it would cause a crash
https://github.com/X9VoiD/VoiDPlugins/releases/tag/vmulti

2020-10-14 22:54 UTC, InfinityGhost requested changes

2020-10-14 22:54 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +            catch (BadImageFormatException e)
Remove unused variable `e`

2020-10-14 23:05 UTC, InfinityGhost requested changes

2020-10-14 23:05 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                if (asm is null) { return false; }
Formatting nitpick lol
```cs
if (asm is null)
    return false;
```

2020-10-14 23:07 UTC, skyborgff commented on OpenTabletDriver/PluginManager.cs
> +                if (asm is null) { return false; }
tbh i wasnt sure the best way to make that. still think it's ugly

2020-10-14 23:08 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                if (asm is null) { return false; }
Agreed, a better way would to add null checking to `GetLoadableTypes()` but this is just a quick and easy way to do it

2020-10-14 23:10 UTC, skyborgff commented on OpenTabletDriver/PluginManager.cs
> +                if (asm is null) { return false; }
That seems inefficient, as we know that that dll `asm` is useless before entering that function.

2020-10-15 15:13 UTC, InfinityGhost approved these changes

2020-10-16 03:28 UTC, merged