Add buttons for FAQ and Plugins
InfinityGhost/OpenTabletDriver pull request #384
Opened 2020-10-17 23:44 UTC by X9VoiD

This makes it easier for people to reach places that are *not* a single click away

2020-10-18 00:15 UTC, InfinityGhost requested changes

2020-10-18 00:15 UTC, InfinityGhost commented on OpenTabletDriver.Native/SystemInfo.cs
> +            }
This shouldn't be required, `Open(string path)` should handle MIME types such as directories and files

2020-10-18 10:54 UTC, X9VoiD commented on OpenTabletDriver.Native/SystemInfo.cs
> +            }
Yeah, opening folders with `Open()` also works on my Windows, but on my Linux it opens up as a VSCode workspace, so I directly used dbus to open a folder using the default file manager

2020-10-18 17:07 UTC, InfinityGhost commented on OpenTabletDriver.Native/SystemInfo.cs
> +            }
Your MIME types are misconfigured then, it should use your file manager. `xdg-open` for a directory path opens in `nemo` for me like it is supposed to.

2020-10-18 17:08 UTC, InfinityGhost commented on OpenTabletDriver.Native/SystemInfo.cs
> +            }
Relying on dbus to do this causes problems with i3 and other minimal window managers as well.

2020-10-19 18:43 UTC, X9VoiD commented on OpenTabletDriver.Native/SystemInfo.cs
> +            }
Change pushed

2020-10-20 14:15 UTC, InfinityGhost commented
lg2m

2020-10-20 14:15 UTC, InfinityGhost approved these changes

2020-10-20 14:15 UTC, merged