Make UX generally safer from wrong input
InfinityGhost/OpenTabletDriver pull request #393
Opened 2020-10-20 21:07 UTC by X9VoiD

# Changes

- Made all user-editable text boxes (except Configuration Editor) restricted to numbers only where suitable
- Made OutputModeSelector readonly
- Added `InputRestrictionAttribute` for plugins which support
    - `InputRestriction.Number`
    - `InputRestriction.Custom`

# Fixes

- UX crash when typing on OutputModeSelector
- UX crash / unstable state when applying or saving invalid input

2020-10-29 23:49 UTC, InfinityGhost requested changes

2020-10-29 23:49 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Attributes/InputRestrictionAttribute.cs
> +        public Restrictor CustomRestrictor { private set; get; }
Could be replaced with `Func<bool, string>`

2020-10-29 23:49 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Attributes/InputRestrictionAttribute.cs
> +    }
Move this to its own file

2020-10-29 23:49 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/PluginSettingsEditor.cs
> +
Wrap this in parenthesis like this, along with the other cases. It allows us to reuse variable names and IMO looks prettier lol
```cs
case InputRestrictionAttribute inputAttr:
{
    if (control is TextBox textBox)
    {
        switch (inputAttr.Restriction)
        {
            case InputRestriction.Number:
                textBox.TextChanging += UXTools.RestrictToNumber;
                break;
            case InputRestriction.Custom:
                textBox.TextChanging += (_, args) =>
                {
                    args.Cancel = inputAttr.CustomRestrictor(args.NewText);
                };
                break;
        }
        return textBox;
    }
    return control;
}
```

2020-10-29 23:49 UTC, InfinityGhost commented on OpenTabletDriver.UX/Tools/UXTools.cs
> +        }
Move this to the `NumberBox` class, I don't see this being used outside of that.

2020-10-30 01:22 UTC, X9VoiD commented
Changes pushed

2020-10-30 01:36 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Attributes/InputRestrictionAttribute.cs
> +        }
Might be a good idea to add another constructor that leaves `customRestrictor` null

2020-10-30 01:39 UTC, InfinityGhost commented on OpenTabletDriver.UX/Tools/NumberBox.cs
> +}
This belongs in the `OpenTabletDriver.UX.Controls` namespace

2020-10-30 04:03 UTC, X9VoiD commented
Changes pushed and tested. `RestrictionType.Hex` for plugins also tested.

2020-10-30 04:05 UTC, X9VoiD commented
PR ready for merge

2020-10-30 15:50 UTC, InfinityGhost requested changes

2020-10-30 15:50 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/HexBox.cs
> +                }
```cs
int.TryParse(this.Text, out var val) ? val : 0;
```

2020-10-30 15:50 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/NumberBox.cs
> +namespace OpenTabletDriver.UX.Tools
Why did you put this in tools lol

2020-10-30 15:50 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/HexBox.cs
> +            return !Regex.IsMatch(str, "^0x[0-9a-f]+$");
Regex is slower than directly trying to parse
```cs
int.TryParse(str.Replace("0x", string.Empty), NumberStyles.HexNumber, null, out var value) ? value : 0;
```

2020-10-30 15:50 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/HexBox.cs
> +namespace OpenTabletDriver.UX.Tools
Why is this in the tools namespace?

2020-10-30 18:35 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/HexBox.cs
> +            return !Regex.IsMatch(str, "^0x[0-9a-f]+$");
lg2m

2020-10-30 18:36 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/HexBox.cs
> +            return !Regex.IsMatch(str, "^0x[0-9a-f]+$");
Just use `string.Empty` instead of `""`

2020-10-31 04:23 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                        dynamic value;
Why not just define this as an object?

2020-10-31 04:33 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                        dynamic value;
I did not know at the time that an object will suffice. Change pushed.

2020-11-03 21:17 UTC, InfinityGhost requested changes

2020-11-03 21:17 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/HexBox.cs
> +        }
Improve naming to something more comprehensive, make the regex static.

2020-11-06 00:56 UTC, InfinityGhost commented
Should we hold this off until v0.4.3?

2020-11-26 20:41 UTC, X9VoiD commented
As discussed, this PR will be closed and branch will be kept for reference. Proposed changes will be rewritten from scratch.

2020-11-26 20:41 UTC, closed without merging