Rework plugin loading
InfinityGhost/OpenTabletDriver pull request #420
Opened 2020-11-03 20:17 UTC by X9VoiD

## Changes

- Rewritten loading logic from scratch.
- Allow plugins (contained in a subdirectory) to load unmanaged dll dependency of their dependencies.
- Unified loading logic for Daemon and UX.
- Lock-less parallel loading wherever possible.

## Tested

- [x] Plugin loading
- [ ] Unmanaged dll loading

2020-11-04 03:30 UTC, X9VoiD commented
Unmanaged dll loading is tested working now.

![Screenshot from 2020-11-04 11-20-25](https://user-images.githubusercontent.com/10338031/98066124-fdf8d880-1e90-11eb-955d-346a125e7b49.png)

2020-11-05 22:21 UTC, InfinityGhost requested changes

2020-11-05 22:21 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                        select type;
Readd the original try load assembly method here

2020-11-05 22:21 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
>              }
This shouldn't be needed, Log.Write just invokes an event which shouldn't cause any threading issues.

2020-11-06 18:21 UTC, X9VoiD commented
Changes pushed.

2020-11-15 05:18 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                }
Why did this change? If anything we should match it on ITool as well if we are going to keep it.

2020-11-15 05:20 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                }
Ah, right. Then should we change ITool to return void instead of bool?

2020-11-15 05:21 UTC, InfinityGhost commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                }
Might as well, but this isn't a change for this type of PR imo.

2020-11-15 05:23 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                }
I see, will revert it then for this PR.

2020-11-15 05:38 UTC, X9VoiD commented on OpenTabletDriver.Daemon/DriverDaemon.cs
> +                }
Revert request is pushed.

2020-11-16 01:50 UTC, InfinityGhost requested changes

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                Log($"Loading deprecated plugin '{plugin}'");
Would prefer to call them something like "global plugins" which don't depend on anything besides the base plugin library.

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                    Log($"Plugin '{type.FullName}' ignored", LogLevel.Debug);
Do not log cases of ignored plugins.

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                    Log($"Plugin '{type.FullName}' incompatible with current OS", LogLevel.Warning);
```cs
Log($"Plugin '{type.FullName}' is not supported on {SystemInfo.CurrentPlatform}", LogLevel.Info);
```

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                                               select ctor;
4 spaces for tabbing in LINQ queries, keeps tabbing consistent.

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +
Spacing pls

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +
Dood

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                        select type;
LINQ query tabbing, 4 spaces

2020-11-16 01:50 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                           select type;
You probably get the gist lol

2020-11-16 03:50 UTC, X9VoiD commented on OpenTabletDriver/PluginManager.cs
> +                Log($"Loading deprecated plugin '{plugin}'");
Will stand-alone plugin work? or independent.

2020-11-16 04:21 UTC, X9VoiD commented
Requested changes pushed

2020-11-16 04:37 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                Log($"Loading deprecated plugin '{plugin}'");
Standalone implies something different, and independent might be the closest thing to it.

2020-11-16 04:39 UTC, InfinityGhost requested changes

2020-11-16 04:39 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +                                                             select type;
Tabbing again lol

2020-11-16 04:46 UTC, X9VoiD commented on OpenTabletDriver/PluginManager.cs
> +                                                             select type;
Pushed. I made sure that I missed nothing now lol

2020-11-16 17:40 UTC, InfinityGhost commented on OpenTabletDriver/PluginManager.cs
> +        }
I think we could remove the need for this function along with the silent variable by moving the `Log.Message` event hook after plugin loading

2020-11-18 20:23 UTC, InfinityGhost approved these changes

2020-11-18 20:33 UTC, merged