Match device to config attributes to improve device selection
InfinityGhost/OpenTabletDriver pull request #425
Opened 2020-11-05 23:18 UTC by X9VoiD

## Changes

- Add new Windows-specific `Attributes`.
  - `WinInterface` to match interface using the HID path.
  - `WinUsage` to match HID usage using the HID path.
- Future proof possible additional attributes by matching differently on Aux and Digitizer.

After fiddling around with the initial `WinDeviceMatchesEndpoint()` idea, I think we need to put `Attributes` inside `DigitizerIdentifiers` and `AuxIdentifiers`. This change will be useful for when Windows somehow decides to separate touch, sliders, wheels, stuff, and to clean up the code this PR currently have.

2020-11-16 01:41 UTC, InfinityGhost requested changes

2020-11-16 01:41 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +            }
Clean up to this, or something similar. Worst case scenario, replace the breaks with `default` and return true.
```cs
private bool DigitizerMatchesAttribute(HidDevice device, Dictionary<string, string> attributes)
{
    var devName = device.GetFileSystemName();

    bool interfaceMatches = attributes.ContainsKey("WinInterface") ? Regex.IsMatch(devName, $"&mi_{attributes["WinInterface"]}") : true;
    bool keyMatches = attributes.ContainsKey("WinUsage") ? Regex.IsMatch(devName, $"&col{attributes["WinUsage"]}") : true;

    return SystemInfo.CurrentPlatform switch 
    {
        RuntimePlatform.Windows => interfaceMatches && keyMatches,
        _ => true
    };
}
```

2020-11-16 01:41 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +            return true; // Future proofing
Might as well implement this ahead of time, but realistically this function shouldn't need to exist because it takes the same arguments as `DigitizerMatchesAttribute()` already covers it and should be used as a generic case.

2020-12-13 14:53 UTC, X9VoiD commented
Requested change pushed, but can't remove the similar functions since we have to differentiate between digitizer and aux. The aux don't need the WinUsage and WinInterface *yet*. When that time comes we will have to move configuration `Attributes` to inside `DigitizerIdentifier` and `AuxiliaryIdentifier`

2020-12-14 06:33 UTC, InfinityGhost approved these changes

2020-12-14 06:35 UTC, merged