[WIP] Plugin Manager
InfinityGhost/OpenTabletDriver pull request #429
Opened 2020-11-07 11:26 UTC by X9VoiD

# Changes

- [x] Plugin Manager window
  - [ ] Show all plugins installed on `PluginDirectory`
  - [ ] (Optional) Plugin status: `loaded`, `loaded (deprecated)`, `incompatible os`, `incompatible type`
- [x] Drag and drop functionality (on supported platforms, see [Eto #1812](https://github.com/picoe/Eto/issues/1812))
- [ ] Manual `File -> Install plugin...`
- [ ] (Optional) Plugin info: `Name`, `Types`, `Source Code URL`

Depends on #420

2020-11-15 11:25 UTC, X9VoiD commented
[(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧](https://streamable.com/q0rm9f#)

2020-11-16 02:03 UTC, InfinityGhost commented
Still more to do, a method to uninstall plugins would also be a nice touch. I'll probably rework the list to have those additional buttons and handle them appropriately.

2020-11-16 03:14 UTC, X9VoiD commented
Uninstalling will be hard since plugins are open files when they are loaded. Windows can't delete them during runtime. Can probably do it during a daemon restart but that would mean Linux will be left behind as it can't restart Daemon (since we rely on the user on how to start the daemon as "daemon"). Same thing with updating loaded plugins, we can only do that with daemon restart.

2020-11-16 04:50 UTC, X9VoiD commented
Will merge `plugin-rework` changes after it is merged, to avoid unneeded extra merge commits.

2020-12-13 05:32 UTC, InfinityGhost commented
I'm fine with this in its current state, the other features will be added with the addition of a plugin repository.

2020-12-13 17:37 UTC, InfinityGhost requested changes

2020-12-13 17:37 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +        public static MainForm FormInstance { get; private set; }
Use `Application.Instance.MainForm` instead and cast it to `MainForm` where needed.

2020-12-13 17:43 UTC, X9VoiD commented on OpenTabletDriver.UX/MainForm.cs
> +        public static MainForm FormInstance { get; private set; }
Pushed

2020-12-13 23:55 UTC, InfinityGhost requested changes

2020-12-13 23:55 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Reflection/PluginStateManager.cs
> +        public FileInfo UninstallCommands = new FileInfo(Path.Join(AppInfo.Current.PendingPluginDirectory, "uninstallCommands.txt"));
This is a bad way to go about this, is this the only option for enqueuing deletion/update?

2020-12-14 12:39 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Reflection/PluginStateManager.cs
> +        public FileInfo UninstallCommands = new FileInfo(Path.Join(AppInfo.Current.PendingPluginDirectory, "uninstallCommands.txt"));
Yeah, the only reasonable way we can do deletion and update is by doing it before `PluginManager` loads the plugins.

The global mutex is there to ensure that whichever runs first (daemon or ux), `PluginStateManager` will complete (and cleanup all enqueued stuff) before the current and other `PluginManager` loads plugins.

We may explore other methods to enqueue deletion, but the update procedure is the simplest it could be. Atleast that's what I think with what I currently know.

2020-12-14 22:08 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Reflection/PluginStateManager.cs
> +        public FileInfo UninstallCommands = new FileInfo(Path.Join(AppInfo.Current.PendingPluginDirectory, "uninstallCommands.txt"));
I think the best method we could have is to move any to-be-deleted files to a trash directory. From there, on next startup that trash directory could be cleared, and wouldn't be any need to check if the file is queued to be deleted. Not only that, but it could be used for client updates as well.

2020-12-21 03:21 UTC, InfinityGhost approved these changes

2020-12-21 03:21 UTC, merged