Update H610 Pro.json
InfinityGhost/OpenTabletDriver pull request #443
Opened 2020-11-13 03:51 UTC by Mrcubix

#Verification

[Discord](https://discord.com/channels/615607687467761684/615611007951306863/776255435647746048)

Tested and working in VC after slapping windows with replug

2020-11-13 06:48 UTC, InfinityGhost requested changes

2020-11-13 06:48 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Huion/H610 Pro.json
> +	  ]
Don't modify an old identifier, duplicate it and make changes.

2020-11-13 07:00 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Huion/H610 Pro.json
> +	  ]
The old identifier was suspicious anyway so imo this change is fine. Index 200 never had any value before, and InputReportLength 4 is weird

2020-11-14 04:45 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Huion/H610 Pro.json
> +	  ]
Hmm understandable

2020-11-14 07:35 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Huion/H610 Pro.json
>      }
As reviewed, this is not needed anymore and should be removed, revert the commit with `git reset HEAD~1` then `git push --force` to delete it without extra "revert" commit.

2020-11-15 05:16 UTC, InfinityGhost approved these changes

2020-11-16 01:28 UTC, merged