Implement rotation in RelativeMode, move deltaing to the end of a pipeline
InfinityGhost/OpenTabletDriver pull request #462
Opened 2020-11-20 12:08 UTC by AbstractQbit

Rotation is done via a transform matrix, along with a sensitivity scaling.
Moving delta creation to the end allows filters to work with position instead of velocity, which they were not designed to handle.

2020-11-20 12:15 UTC, X9VoiD commented
Am not against the change, but just wanna say that this breaks [PrecisionControl](https://github.com/X9VoiD/VoiDPlugins/blob/master/PrecisionControl/PrecisionControl.cs#L50).

Will clean up the code tho since we don't have to check if it's RelativeOutputMode anymore. Will also fix all other filters since only PrecisionControl handles relative data lol

2020-11-20 12:21 UTC, AbstractQbit commented
The idea was that you won't have to fix all the other filters, since now they should work the same as in absolute mode

2020-11-22 07:20 UTC, InfinityGhost requested changes
Looks good, just one rename and I'm happy with it

2020-11-22 07:20 UTC, InfinityGhost commented on OpenTabletDriver/Settings.cs
> +        }
Rename to `RelativeRotation`, avoid shortened names for major properties like this.

2020-11-22 17:02 UTC, InfinityGhost approved these changes

2020-11-25 07:39 UTC, InfinityGhost requested changes

2020-11-25 07:39 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/RelativeOutputMode.cs
> +                (float)(_rotation * System.Math.PI / 180));
Invert rotation to match AbsoluteOutputMode

2020-11-25 08:20 UTC, InfinityGhost approved these changes

2020-11-25 08:23 UTC, merged