Improve logging safety
InfinityGhost/OpenTabletDriver pull request #464
Opened 2020-11-21 18:00 UTC by X9VoiD

Internally synchronize all calls to AddItem to avoid race conditions

2020-11-22 17:07 UTC, InfinityGhost approved these changes

2020-11-23 04:16 UTC, InfinityGhost requested changes

2020-11-23 04:16 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/LogView.cs
> +                lock (logLock)
After some testing, locking in this way deadlocks the UX thread. A concurrent collection should be used instead to avoid this issue.

2020-11-23 08:09 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/LogView.cs
> +                lock (logLock)
Requested changes pushed.

![image](https://user-images.githubusercontent.com/10338031/99939887-f30ec680-2d1f-11eb-8f6e-89f88cb510c3.png)

Not only did it lower memory usage from 3.1GB to 100MB, but the test itself run from 2-3 minutes down to just 2 seconds.

2020-11-24 08:11 UTC, InfinityGhost approved these changes
Absolutely fantastic changes here. Have yet to test it, but this looks like it should resolve the thread blocking being that it uses concurrent collections.

2020-11-25 07:04 UTC, merged