Fix unmanaged library loading
InfinityGhost/OpenTabletDriver pull request #465
Opened 2020-11-22 09:24 UTC by X9VoiD

Thanks to @AbstractQbit for debugging this issue.

2020-11-22 17:09 UTC, InfinityGhost requested changes

2020-11-22 17:09 UTC, InfinityGhost commented on OpenTabletDriver/PluginContext.cs
> +                throw new NotImplementedException();
```cs
throw new NotSupportedException();
```

2020-11-23 06:30 UTC, X9VoiD commented on OpenTabletDriver/PluginContext.cs
> +                throw new NotImplementedException();
Requested change pushed

2020-11-25 04:42 UTC, InfinityGhost commented on OpenTabletDriver/PluginContext.cs
>                  return LoadUnmanagedDllFromPath(libraryFile);
Does this intend to call `base.LoadUnmanagedDllFromPath()` or `this.LoadUnmanagedDllFromPath()`

2020-11-25 04:54 UTC, X9VoiD commented on OpenTabletDriver/PluginContext.cs
>                  return LoadUnmanagedDllFromPath(libraryFile);
`LoadUnmanagedDllFromPath` cannot be overriden, so this line calls `base.LoadUnmanagedDllFromPath()`

2020-11-25 06:42 UTC, InfinityGhost approved these changes

2020-11-25 07:06 UTC, InfinityGhost approved these changes

2020-11-25 07:06 UTC, InfinityGhost commented
lol approved twice

2020-11-25 07:06 UTC, merged