Add config for PTK-440
InfinityGhost/OpenTabletDriver pull request #478
Opened 2020-11-26 14:29 UTC by X9VoiD

## Verification

[Discord](https://discord.com/channels/615607687467761684/615611007951306863/781523609990332456)

Thanks to Zabergan#8888 for doing most of the config 🥖

2020-11-26 17:23 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Wacom/PTK-440.json
> +  ],
Why is this defined without input report length or output report length?

2020-12-02 21:25 UTC, InfinityGhost requested changes

2020-12-02 21:25 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Wacom/PTK-440.json
> +    }
This must be defined with an input report length or output report length to look for. Just like this is a bit questionable

2020-12-03 11:36 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/PTK-440.json
> +    }
Yeah, forgot to work on this again lmao. IntuosV2 share the same interface for tablet and aux data. Requested change pushed.

2020-12-03 17:38 UTC, InfinityGhost approved these changes

2020-12-03 17:38 UTC, merged