Add initial Wacom multitouch parsing functionality
InfinityGhost/OpenTabletDriver pull request #480
Opened 2020-11-26 22:13 UTC by AbstractQbit

2020-12-01 22:19 UTC, InfinityGhost requested changes

2020-12-01 22:41 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Tablet/Touch/ITouchReport.cs
> +        TouchPoint?[] Touches { get; }
Makes it easy to address specific finger touches (eg if two fingers were tracked and first one lifts off, the second one will stay on the same place in array), and if no touch is detected, then it's just null. Considering that packets contain only update information, making in not nullable will probably make parsing more complicated. 
And imo it should be easier to work with this data when each touch is addressable by tablet's reported number.

2020-12-01 22:44 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Tablet/Touch/TouchPoint.cs
> +        }
Will do tomorrow. Also will rename someOtherPressure to confidence, as it seems to try differentiating between intentional and accidental touches.

2020-12-01 22:44 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Touch/ITouchReport.cs
> +        TouchPoint?[] Touches { get; }
We could also just make `TouchPoint` a class instead of a struct and no need for marking it nullable like this.

2020-12-01 22:58 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Tablet/Touch/ITouchReport.cs
> +        TouchPoint?[] Touches { get; }
Yeah, that does make sense, will change it to class then

2020-12-10 20:22 UTC, AbstractQbit commented
I'll see what I can do about reading intuosv3 touch data now that I have one to experiment with. Marking as a draft for now.

2021-02-24 20:20 UTC, InfinityGhost commented
This appears to be superseded by #582, closing this drafted PR.

2021-02-24 20:20 UTC, closed without merging