Add Support for Wacom MTE-450, like #482 asked
InfinityGhost/OpenTabletDriver pull request #483
Opened 2020-11-27 18:15 UTC by C0D3-M4513R

2020-11-27 19:07 UTC, X9VoiD commented
For verification purposes, post screenshot of tablet debugger showing highest possible `Position`, and another for `Pressure`.

Also upload a diagnostics file, again.

2020-11-27 19:17 UTC, C0D3-M4513R commented
I will, however the support, that this config provides is right now fluctuating massively. I need to find a better config. I will post results, when I get there. Have been trying to get it to run since then.

2020-11-27 19:23 UTC, C0D3-M4513R commented
It is right now, as if OpenTabletDriver is not actually the active driver for the tablet.

2020-11-27 19:32 UTC, X9VoiD commented
Uninstall the official wacom driver, close OTD, unplug the tablet, replace your config with this one

```js
{
  "Name": "Wacom MTE-450",
  "DigitizerIdentifiers": [
    {
      "Width": 147.6,
      "Height": 92.3,
      "MaxX": 14760.0,
      "MaxY": 9225.0,
      "MaxPressure": 511,
      "ActiveReportID": {
        "Start": null,
        "StartInclusive": false,
        "End": null,
        "EndInclusive": false
      },
      "VendorID": 1386,
      "ProductID": 101,
      "InputReportLength": 8,
      "OutputReportLength": null,
      "ReportParser": null,
      "FeatureInitReport": "AgI=",
      "OutputInitReport": null,
      "DeviceStrings": {},
      "InitializationStrings": []
    },
    {
      "Width": 147.6,
      "Height": 92.3,
      "MaxX": 14760.0,
      "MaxY": 9225.0,
      "MaxPressure": 511,
      "ActiveReportID": {
        "Start": null,
        "StartInclusive": false,
        "End": null,
        "EndInclusive": false
      },
      "VendorID": 1386,
      "ProductID": 101,
      "InputReportLength": 9,
      "OutputReportLength": null,
      "ReportParser": "OpenTabletDriver.Vendors.SkipByteTabletReportParser",
      "FeatureInitReport": "AgI=",
      "OutputInitReport": null,
      "DeviceStrings": {},
      "InitializationStrings": []
    }
  ],
  "AuxilaryDeviceIdentifiers": [],
  "Attributes": {}
}
```
Restart OTD, then do the verification steps.

2020-11-27 19:57 UTC, C0D3-M4513R commented
It works without the `"FeatureInitReport": "AgI=",` too. I'm leaving that in there, since I don't exactly know, what that does

2020-11-27 19:57 UTC, C0D3-M4513R commented
![grafik](https://user-images.githubusercontent.com/28912031/100481001-2e7c0d00-30f3-11eb-80dc-37d74527dcc4.png)

2020-11-27 20:05 UTC, C0D3-M4513R commented
![2020-11-27 21 04 03](https://user-images.githubusercontent.com/28912031/100481385-38524000-30f4-11eb-915f-f9d8a25a5e69.png)

2020-11-27 20:12 UTC, C0D3-M4513R commented
[sdgfgsdf.txt](https://github.com/InfinityGhost/OpenTabletDriver/files/5609453/sdgfgsdf.txt)

2020-11-28 04:15 UTC, InfinityGhost commented
> It works without the `"FeatureInitReport": "AgI=",` too. I'm leaving that in there, since I don't exactly know, what that does

In very few cases, such as if the Wacom driver is installed it can help to prepare the device to read data.

Btw `AgI=` is Base64 for `0x02 0x02` lol

2020-11-28 20:24 UTC, InfinityGhost commented
Before this gets merged, I want to notify you that we plan on switching licenses from GPLv3 to LGPLv3. If you don't agree to the change, we won't merge this pull request.

2020-11-29 01:30 UTC, C0D3-M4513R commented
I agree

2020-12-01 05:13 UTC, InfinityGhost commented
@X9VoiD @C0D3-M4513R is this correctly tested and ready for merge?

2020-12-01 06:11 UTC, C0D3-M4513R commented
@InfinityGhost 
Have been using this config for 2 days without issues. Pen position, pen touch strength and pen buttons are working as well.
The tablet buttons are working as well. 

The only unsupported feature of the tablet would be, that the zoom circle is actually being detected as 2 buttons, which actually don't do anything.

2020-12-01 06:13 UTC, InfinityGhost commented
I'm mostly concerned about the dimensions being correctly calculated, LPI and width/height should be matching the MaxX and MaxY. If we can confirm this we're g2g

2020-12-01 06:58 UTC, X9VoiD requested changes

2020-12-01 06:58 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/MTE-450.json
> +      "Height": 92.3,
```js
"Height": 92.25
```

2020-12-01 06:58 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/MTE-450.json
> +      "Height": 92.3,
```js
"Height": 92.25
```

2020-12-01 06:58 UTC, C0D3-M4513R commented
> I'm mostly concerned about the dimensions being correctly calculated, LPI and width/height should be matching the MaxX and MaxY. If we can confirm this we're g2g

14760 MaxX/ 2540 lpi * 25,4(conversion from i to mm) =147,6 mm width
9225 MaxX: 2540 lpi * 25,4(conversion from i to mm) =92,25 mm height

2020-12-01 16:29 UTC, X9VoiD approved these changes

2020-12-01 16:29 UTC, merged