Move all OpenTabletDriver desktop-oriented classes to OpenTabletDriver.Desktop
InfinityGhost/OpenTabletDriver pull request #488
Opened 2020-11-29 08:03 UTC by InfinityGhost

# Changes
- Moves all classes related to the OpenTabletDriver desktop experience to its own library
- Bindings are only used in the OpenTabletDriver.Desktop implementation
- Many naming changes for clarity

| Old                | New                |
| ------------------ | ------------------ |
| `IVirtualTablet`   | `IAbsolutePointer` |
| `IVirtualMouse`    | `IRelativePointer` |
| `IVirtualPointer`  | `IVirtualMouse`    |
| `IPressureHandler` | `IVirtualTablet`   |

2020-11-29 19:30 UTC, X9VoiD requested changes

2020-11-29 19:30 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        private Lazy<EvdevVirtualTablet> penHandler = new Lazy<EvdevVirtualTablet>();
Since this is not a static class we can lose `Lazy<>` here
```cs
private EvDevVirtualTablet penHandler = new EvDevVirtualTablet()
```

2020-11-29 19:30 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IVirtualScreen VirtualScreen => throw new NotImplementedException();
Is this intended? or
```cs
public override IVirtualScreen VirtualScreen => Platform.VirtualScreen;
```

2020-11-29 19:30 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IAbsolutePointer Pointer => penHandler.Value;
```cs
public override IAbsolutePointer Pointer => penHandler;
```

2020-11-29 19:31 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Output/LinuxArtistMode.cs
> +        public override IVirtualScreen VirtualScreen => throw new NotImplementedException();
Good catch

2020-12-01 00:30 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/TabletStatus.cs
> +    public class TabletState
Rename `TabletStatus.cs` -> `TabletState.cs`

2020-12-01 00:38 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/ConfigurationEditor.cs
> +
We need a serialization helper class instead of this jank mess

2020-12-01 00:38 UTC, InfinityGhost commented on OpenTabletDriver/Reflection/PluginManager.cs
> +            return null;
Probably would be better to throw an exception instead of returning null, could reduce some pains.

2020-12-01 00:54 UTC, InfinityGhost commented on OpenTabletDriver/Reflection/PluginManager.cs
> +            return null;
Will change this later in a different PR where needed. Too much depends on this returning null, so we just will leave it be for now.

2020-12-01 02:29 UTC, merged