Add FilterStage.PreInterpolate
InfinityGhost/OpenTabletDriver pull request #502
Opened 2020-12-02 13:54 UTC by X9VoiD

This is required for filters that need to work on the rawest form of the tablet data.

An example of this is the [Reconstructor](https://github.com/X9VoiD/VoiDPlugins/tree/master/Reconstructor) filter where changing the report rate or the position by any means will affect its accuracy negatively.

2020-12-02 21:11 UTC, InfinityGhost requested changes

2020-12-02 21:11 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        protected List<IFilter> filters = new List<IFilter>();
Whats the sense in storing this as a list?

2020-12-03 07:54 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        protected List<IFilter> filters = new List<IFilter>();
Same reason as to why we keep other filters as list per stages. Enumerating over an IEnumerable with `foreach` calls the constructor of the filter, making any settings and filter internal state to be reset.

2020-12-03 07:56 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        protected List<IFilter> filters = new List<IFilter>();
May also probably just use `IFilter[]` instead of `List<IFilter>` if you prefer that.

2020-12-05 19:37 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        protected List<IFilter> filters = new List<IFilter>();
Use `IList<IFilter>` in place of `List<IFilter>`, it would cover our use case. `T[]` derives `IList<T>`, its the bare minimum for what we need.

2020-12-06 21:14 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        protected List<IFilter> filters = new List<IFilter>();
Requested changes pushed

2020-12-06 21:35 UTC, InfinityGhost requested changes

2020-12-06 21:35 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        }
`IList<IFilter>`, I'd prefer to avoid internally casting or converting

2020-12-07 09:11 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +        }
a

2020-12-07 19:28 UTC, InfinityGhost approved these changes

2020-12-07 19:28 UTC, merged