Use HPET-enabled Stopwatch class
InfinityGhost/OpenTabletDriver pull request #575
Opened 2020-12-20 11:57 UTC by AbstractQbit

It replaces DateTime.Now in ms-critical sections,
as per .net documentation, DateTime.Now's resolution
can have an impact on sub 100ms time intervals.
https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=net-5.0#datetime-resolution

2020-12-23 02:12 UTC, InfinityGhost requested changes

2020-12-23 02:12 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Output/RelativeOutputMode.cs
> +        private bool skipReport = false;
I think it might be a good idea to create a base class for classes that need HPET

2020-12-23 16:27 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Output/RelativeOutputMode.cs
> +        private bool skipReport = false;
Change pushed

2021-01-01 18:58 UTC, InfinityGhost commented
The stopwatch based timer is only more accurate than `DateTime.Now` when the hardware supports it, and having a constantly running stopwatch also can have performance penalties.

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch.ishighresolution?view=net-5.0#remarks

2021-01-01 18:59 UTC, InfinityGhost requested changes

2021-01-01 18:59 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +        private static Stopwatch internalWatch = Stopwatch.StartNew();
Not a good idea to mark this as static, since it will always be running, even when no HPET timers are needed.

2021-01-01 19:06 UTC, InfinityGhost requested changes

2021-01-01 19:06 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +        public double RestartMs() => Restart().TotalMilliseconds;
Remove these unnecessary helper methods, since they're only referenced like twice ever

2021-01-01 19:06 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +    public class DeltaStopwatch
Change namespace to `OpenTabletDriver.Plugin.Timing` and class name to `HighPrecisionEventStopwatch`

2021-01-01 19:06 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +    public class DeltaStopwatch
Do we really need a wrapper for an already existing class? This seems kinda pointless.

2021-01-01 21:53 UTC, AbstractQbit commented
> The stopwatch based timer is only more accurate than `DateTime.Now` when the hardware supports it, and having a constantly running stopwatch also can have performance penalties.

HPET was introduced by intel in ~2005 and is included in basically every platform since. It starts runing at a system startup and only ever costs you anything when you query it. The wrapper is there so that we can "lap" the stopwatch with just 1 kernel call/HPET query instead of two when querying elapsed and then restarting. This also eliminates the possibility of missing some ticks between checking the time and restarting.

2021-01-01 21:56 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +        private static Stopwatch internalWatch = Stopwatch.StartNew();
If it's never used, then it just means one HPET query at static init phase, nothing more. There is really no difference between having it static vs non-static, apart from having a couple more objects and not being able to query total app runtime in non-static case.

2021-01-01 22:14 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +    public class DeltaStopwatch
DeltaStopwach name was used because it allows for measuring laps without redundant queries, in contrast to regular Stopwatch. HighPrecisionEventStopwatch doesn't really reflect the difference between those classes, and is very long imo

2021-01-01 22:19 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +        public double RestartMs() => Restart().TotalMilliseconds;
If it looks out of place, then sure, will remove those. Made them because most of the time milliseconds are what's being used in the end.

2021-01-01 23:49 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +        private static Stopwatch internalWatch = Stopwatch.StartNew();
Leave this as is then.

2021-01-01 23:51 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +        public double RestartMs() => Restart().TotalMilliseconds;
Just looks odd for it to be exposed like that the main method going unused

2021-01-01 23:55 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Utils/DeltaStopwatch.cs
> +    public class DeltaStopwatch
Class name length isn't an issue. Can we compromise on `HPETDeltaStopwatch` as the class name?

2021-01-02 04:48 UTC, InfinityGhost approved these changes

2021-01-02 04:49 UTC, merged