Add Eraser and Tilt recognition
InfinityGhost/OpenTabletDriver pull request #582
Opened 2020-12-24 17:06 UTC by AbstractQbit

Eraser is basically only detected on intuosv3 right now, on intuosv2 toolID determines if it's an eraser, and for other tablets idk where the eraser bit is.

2020-12-24 18:37 UTC, InfinityGhost commented
Move tilt and eraser into their own interfaces, `ITiltReport` and `IEraserReport`

2020-12-26 03:57 UTC, InfinityGhost requested changes

2020-12-26 03:57 UTC, InfinityGhost commented on OpenTabletDriver/Tablet/TabletReport.cs
> +    public struct TabletReport : ITabletReport, ITiltReport
Not all generic HID tablets support tilt from what I can tell, revert this to standard. Create a separate IntuosV1Report for the 470, 471, 480, etc. since they do contain this data.

2020-12-26 04:28 UTC, InfinityGhost commented
All that is really left for this to be complete is making it work and readable with the tablet debugger.

2020-12-26 04:35 UTC, X9VoiD commented on OpenTabletDriver/Tablet/TabletReport.cs
> +    public struct TabletReport : ITabletReport, ITiltReport
UC Logic tablets uses this same logic so it may be named as `ExtendedTabletReport` (signifying that it is just an extension of the standard parser) or something . Or probably just check if report size is more than 10.

2020-12-26 04:37 UTC, InfinityGhost commented on OpenTabletDriver/Tablet/TabletReport.cs
> +    public struct TabletReport : ITabletReport, ITiltReport
> Or probably just check if report size is more than 10.

Maybe in the report parser, but not directly within the report class. IntuosV1 also reports eraser, tilt, and hover height detection, so that's something we should also try to confirm if its used in UCLogic tablets as well.

2021-02-22 17:12 UTC, AbstractQbit commented
Redid this pr because changes here were incompatible with visualizer

2021-02-23 17:56 UTC, InfinityGhost requested changes

2021-02-23 17:56 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/IDeviceReport.cs
> +        string GetStringFormat() => "";
I like this change, however maybe we should just make it pull the raw report when its just an IDeviceReport.
```suggestion
        string GetStringFormat() => GetStringRaw();
```

2021-02-23 17:56 UTC, InfinityGhost commented on OpenTabletDriver/Tablet/TabletReportParser.cs
> +                return new TiltTabletReport(data);
Might need to test this out, could potentially cause huge issues.

2021-02-23 17:56 UTC, InfinityGhost commented on OpenTabletDriver/Tablet/TabletReportParser.cs
> +                return new TiltTabletReport(data);
We should instead add another report parser, keeping this one vanilla without any frills. Add a `TabletTiltReportParser` class inheriting this class with these changes with an override of this method.

2021-02-24 20:22 UTC, InfinityGhost approved these changes
LG2M

2021-02-24 20:25 UTC, merged