Add Deco Pro Small configuration
InfinityGhost/OpenTabletDriver pull request #592
Opened 2020-12-29 05:50 UTC by X9VoiD

## Verification

[Discord](https://discord.com/channels/615607687467761684/789348845372178482/793353604861919232)

2021-02-24 20:57 UTC, InfinityGhost requested changes
very late review lol

2021-02-24 20:57 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/XP-Pen/Deco Pro Small.json
> +      "ReportParser": null,
Use explicit report parser

2021-02-25 05:05 UTC, X9VoiD commented on OpenTabletDriver/Configurations/XP-Pen/Deco Pro Small.json
> +      "ReportParser": null,
Fixed

2021-02-27 21:35 UTC, InfinityGhost approved these changes
No auxiliary support, marking as missing features.

2021-02-27 21:36 UTC, merged