Add Configuration For Wacom Intuos 4 XL ( PTK-1240 )
InfinityGhost/OpenTabletDriver pull request #593
Opened 2020-12-29 11:24 UTC by insomnyawolf

I've been using this for a while and seems to cause no issues yet so far, if you need anything else, tell me

2020-12-29 12:04 UTC, X9VoiD requested changes

2020-12-29 12:04 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/PTK-1240.json
> +        "StartInclusive": true,
Other IntuosV2 tablets needed
```
"Start": 1,
"StartInclusive": false
```
to avoid occasional cursor teleport when tablet is not in use but still connected. Can you verify that the same issue is not happening with this tablet? If it's happening then change the range to the one I wrote here.

2020-12-29 12:04 UTC, X9VoiD commented on OpenTabletDriver/Configurations/Wacom/PTK-1240.json
> +        "StartInclusive": true,
Same here

2020-12-29 14:14 UTC, insomnyawolf commented on OpenTabletDriver/Configurations/Wacom/PTK-1240.json
> +        "StartInclusive": true,
I didn't had this issue yet, the only similar thing that happen is cursor teleport if i click the buttons on the tablet.

I'm testing it with this edit just in case, i'll keep you updated.

2020-12-29 21:42 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/Wacom/PTK-1240.json
> +        "StartInclusive": true,
> the only similar thing that happen is cursor teleport if i click the buttons on the tablet

That might be due to this range issue.

2021-01-12 08:33 UTC, insomnyawolf commented
I've tested it a little bit and it seems to be working fine, thanks for the feedback

2021-01-12 12:03 UTC, X9VoiD approved these changes

2021-01-14 19:12 UTC, InfinityGhost approved these changes

2021-01-14 19:12 UTC, merged