Silently fail when HID feature or output fails
InfinityGhost/OpenTabletDriver pull request #599
Opened 2020-12-30 10:12 UTC by X9VoiD

2020-12-30 18:54 UTC, InfinityGhost requested changes

2020-12-30 18:54 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +                    Log.Debug("Device", $"HID Feature '{BitConverter.ToString(featureInitReport)}' succesfully set");
```cs
Log.Debug("Device", "Set aux feature: " + BitConverter.ToString(featureInitReport));
```

2020-12-30 18:54 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +                catch {}
Log failed `SetFeature` instead of failing completely silently
```cs
catch
{
    Log.Write("Device", "Failed to set feature: " + BitConverter.ToString(featureInitReport), LogLevel.Warning);
}
```

2020-12-30 18:54 UTC, InfinityGhost commented on OpenTabletDriver/Driver.cs
> +                catch {}
Same here

2021-01-01 09:54 UTC, X9VoiD commented
Requested changes pushed

2021-01-01 18:35 UTC, InfinityGhost approved these changes

2021-01-01 18:36 UTC, merged