Allow only one instance of UX.Wpf
InfinityGhost/OpenTabletDriver pull request #609
Opened 2020-12-31 18:18 UTC by X9VoiD

2021-01-01 18:35 UTC, InfinityGhost requested changes

2021-01-01 18:35 UTC, InfinityGhost commented on OpenTabletDriver.UX/App.cs
> +            var handle = new EventWaitHandle(false, EventResetMode.AutoReset, @"Global\OpenTabletDriver.UX.Wpf", out var host);
Should just use our `Instance` class here, since it does the same thing without requiring an extra thread.

2021-01-02 02:30 UTC, X9VoiD commented on OpenTabletDriver.UX/App.cs
> +            var handle = new EventWaitHandle(false, EventResetMode.AutoReset, @"Global\OpenTabletDriver.UX.Wpf", out var host);
We can't use Instance here since it cannot detect when a new Instance is spawned. It can only work one way. And the thread handling the showing of the window runs on the host, not on the new one.

2021-01-02 03:05 UTC, InfinityGhost commented on OpenTabletDriver.UX/App.cs
> +            var handle = new EventWaitHandle(false, EventResetMode.AutoReset, @"Global\OpenTabletDriver.UX.Wpf", out var host);
You just detect if an instance already exists, literally copy what the daemon does.

2021-01-02 03:10 UTC, InfinityGhost approved these changes

2021-01-02 03:10 UTC, InfinityGhost commented on OpenTabletDriver.UX/App.cs
> +            var handle = new EventWaitHandle(false, EventResetMode.AutoReset, @"Global\OpenTabletDriver.UX.Wpf", out var host);
Scratch that, misread the second part. If it has issues in the future we'll deal with it then.

2021-01-08 10:40 UTC, X9VoiD commented
Closing. Superseded by #634

2021-01-08 10:40 UTC, closed without merging