Change Area Converter labels accordingly
InfinityGhost/OpenTabletDriver pull request #612
Opened 2021-01-01 17:03 UTC by X9VoiD

Also changed Group to update layout when changing `Group.Text`, and to avoid performing unneeded layout update during ctor by using the private member instead of the public property during ctor.

2021-01-01 18:32 UTC, InfinityGhost requested changes

2021-01-01 18:32 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/IAreaConverter.cs
> +        string[] Label { get; }
Change this to make it more obvious what order they should be in
```cs
string Left { get; }
string Top { get; }
string Right { get; }
string Bottom { get; }
```

2021-01-02 02:47 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/IAreaConverter.cs
> +        string[] Label { get; }
They go by the order of variables in `Convert()` since left, top, right, bottom don't quite fit XP-Pen's width, height, x-offset, y-offset

2021-01-02 03:02 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/IAreaConverter.cs
> +        string[] Label { get; }
Doesn't matter, since here you can redefine it. XP-Pen is the odd one out on everything here right now

2021-01-02 17:38 UTC, X9VoiD commented on OpenTabletDriver.Plugin/Tablet/IAreaConverter.cs
> +        string[] Label { get; }
Fixed

2021-01-06 20:51 UTC, InfinityGhost requested changes

2021-01-06 20:51 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/AreaConverterDialog.cs
> +
This change is now overkill for what we need, since we're just using the properties. We can basically just revert to what we had before but with the label text being the property.

2021-01-07 04:42 UTC, X9VoiD commented on OpenTabletDriver.UX/Windows/AreaConverterDialog.cs
> +
We still have to keep a reference to the group somehow. I reverted those changes so it won't use arrays anymore, but kept the Group variable so we may refresh `Group.Text`.

2021-01-07 17:57 UTC, InfinityGhost requested changes

2021-01-07 17:57 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/Generic/Group.cs
> +        }
Unnecessary change. Apply this diff instead:
```diff
diff --git a/OpenTabletDriver.UX/Controls/Generic/Group.cs b/OpenTabletDriver.UX/Controls/Generic/Group.cs
index eabc504..eb93847 100644
--- a/OpenTabletDriver.UX/Controls/Generic/Group.cs
+++ b/OpenTabletDriver.UX/Controls/Generic/Group.cs
@@ -57,6 +57,9 @@ namespace OpenTabletDriver.UX.Controls.Generic
 
         protected void UpdateControlLayout()
         {
+            if (!this.Loaded)
+                return;
+
             switch (Orientation, SystemInterop.CurrentPlatform)
             {
                 case (_, PluginPlatform.MacOS):
```

2021-01-07 17:57 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/OutputModeEditor.cs
> +                    await converter.ShowModalAsync(Application.Instance.MainForm);
`await converter.ShowModalAsync(this.ParentWindow);` should be fine

2021-01-07 18:17 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/Generic/Group.cs
> +        }
![image](https://user-images.githubusercontent.com/10338031/103928931-790f9100-5157-11eb-86c1-a9ecdf5dee4c.png)

The control itself is not notified of the change to Text since it's not data binded I think.

2021-01-07 18:22 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/Generic/Group.cs
> +        }
Keep the `Text` change, but don't use the private field to update it's value in the constructor.

2021-01-07 18:32 UTC, X9VoiD commented on OpenTabletDriver.UX/Controls/Generic/Group.cs
> +        }
🍞

2021-01-07 19:35 UTC, InfinityGhost approved these changes

2021-01-07 21:32 UTC, merged