Show default values for plugin settings
InfinityGhost/OpenTabletDriver pull request #618
Opened 2021-01-02 16:22 UTC by X9VoiD

- [x] Filter, Tools
- [ ] Interpolator

2021-01-02 16:23 UTC, X9VoiD commented
Since Interpolator have no parameter-less constructor, we can't inspect its default values yet.

2021-01-06 21:07 UTC, InfinityGhost requested changes
Maintainability is being lost here, a lot of this needs to be reverted and rethought.

2021-01-06 21:07 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Reflection/StoredPluginReference.cs
> +        public T DirectConstruct<T>() where T : class => base.Construct<T>();
If we're going to add this function, we might as well add it with the arguments parameters as well.
```cs
public T BaseConstruct<T>() where T : class => base.Construct<T>();
public T BaseConstruct<T>(params object[] args) where T : class => base.Construct<T>(args);
```

2021-01-06 21:07 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                    this.reportStopwatch.Stop();
Good performance catch

2021-01-06 21:07 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/PluginSettingStoreCollectionEditor.cs
>              }
Keep the original function layout, it was much easier to maintain than this.

2021-01-06 21:07 UTC, InfinityGhost commented on OpenTabletDriver.UX/Controls/PluginSettingStoreCollectionEditor.cs
> +                if (genericControls.TryGetValue(property.PropertyType, out var getGenericTextBox))
RIP attributes, revert this.

2021-01-06 21:12 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                    this.reportStopwatch.Stop();
This doesn't affect performance, but does improve `reportMsAvg` value stability

2021-01-06 21:15 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                    this.reportStopwatch.Stop();
Oh right this is the internal stopwatch, not the event timer

2021-01-06 21:24 UTC, AbstractQbit commented on OpenTabletDriver.Plugin/Tablet/Interpolator/Interpolator.cs
> +                    Info.Driver.ReportRecieved -= HandleReport;
HandleReport can lock itself out at line 89

2021-01-07 02:14 UTC, X9VoiD commented
Did a rewrite of the PR to use attributes instead.

2021-01-07 17:49 UTC, InfinityGhost requested changes

2021-01-07 17:49 UTC, InfinityGhost commented on OpenTabletDriver.Plugin/Attributes/DefaultPropertyValueAttribute.cs
> +        }
Fix this formatting
```cs
public DefaultPropertyValueAttribute(object value)
{
    this.Value = value;
}

public object Value { get; }
```

2021-01-07 17:49 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Reflection/PluginSetting.cs
> +        public bool IsValid => Value != null && Value.Type != JTokenType.Null;
Would prefer this to be named `HasValue`, `IsValid` implies that something is incorrect where we just want to know if it has a value.

2021-01-07 18:10 UTC, X9VoiD commented
Requested changes pushed

2021-01-07 18:19 UTC, InfinityGhost approved these changes

2021-01-07 18:21 UTC, merged