Ensure window visibility and launch Greeter at center position
InfinityGhost/OpenTabletDriver pull request #630
Opened 2021-01-07 10:40 UTC by X9VoiD

# Changes

- OTD Window size at launch will either be the old defaults, or 90% of screen, whichever is smaller on that axis. Helps with 1366x768 monitors where main UX is always too big on launch.
- "Try" to make the whole of OTD window visible on the screen it got launched (Windows only)
- Set MainForm as parent of Greeter so Greeter will always be launched centered on supporting platforms.

Windows 10 somehow don't remember the last window position of OTD and always spawn it randomly; almost always in a way where OTD gets cut off on smaller screens (1366x768)

2021-01-07 17:42 UTC, InfinityGhost requested changes

2021-01-07 17:42 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +            var greeter = new StartupGreeterWindow(Application.Instance.MainForm);
`new StartupGreeterWindow(this)` would suffice

2021-01-07 17:42 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +                this.Shown += VisibilityCheck; // Size and Location becomes available only during and after Shown event, LoadComplete don't have it yet
Override `OnShown` instead

2021-01-07 18:02 UTC, X9VoiD commented on OpenTabletDriver.UX/MainForm.cs
> +                this.Shown += VisibilityCheck; // Size and Location becomes available only during and after Shown event, LoadComplete don't have it yet
Fixed, but made a new variable `this.AlreadyShown` so it only runs on launch (to respect window positioning set by user after launch)

2021-01-07 18:19 UTC, InfinityGhost requested changes

2021-01-07 18:19 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +        private bool AlreadyShown;
Private fields should always be `camelCased`

2021-01-07 18:19 UTC, InfinityGhost commented on OpenTabletDriver.UX/MainForm.cs
> +        private bool AlreadyShown;
Also please add some spacing there, and move the variable along with the other fields.

2021-01-07 18:26 UTC, X9VoiD commented on OpenTabletDriver.UX/MainForm.cs
> +        private bool AlreadyShown;
Fixed

2021-01-07 19:23 UTC, InfinityGhost approved these changes

2021-01-08 19:00 UTC, InfinityGhost commented
> OTD Window size at launch will either be the old defaults, or 90% of screen

This doesn't seem to work, even at 1024x768

2021-01-09 06:09 UTC, X9VoiD commented
Made some changes to correct behavior on multi-monitor setups

2021-01-14 19:39 UTC, InfinityGhost requested changes
One minor change and I'll be happy

2021-01-14 19:39 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Greeter/StartupGreeterWindow.cs
> +        public StartupGreeterWindow(Window parent) : this()
Format this
```cs
public StartupGreeterWindow(Window parent)
    : this()
{
```

2021-01-15 14:09 UTC, X9VoiD commented on OpenTabletDriver.UX/Windows/Greeter/StartupGreeterWindow.cs
> +        public StartupGreeterWindow(Window parent) : this()
Fixed

2021-01-15 20:37 UTC, InfinityGhost approved these changes

2021-01-18 13:22 UTC, InfinityGhost requested changes
This is currently bugged on MacOS, the MainForm position is offset way off center. This needs to be fixed before I can merge this.

2021-01-18 13:40 UTC, X9VoiD commented
Changes pushed. CodeFactor did an oopsie.

2021-01-18 14:37 UTC, InfinityGhost commented
Odd that `SA1106` was triggered, will have to make an issue there.

2021-01-18 15:10 UTC, InfinityGhost approved these changes

2021-01-18 15:10 UTC, merged