Add Deco Mini7 Configuration
InfinityGhost/OpenTabletDriver pull request #705
Opened 2021-01-22 09:47 UTC by Devrulx

2021-01-22 09:53 UTC, X9VoiD requested changes

2021-01-22 09:53 UTC, X9VoiD commented on OpenTabletDriver/Configurations/XP-Pen/Deco mini7.json
> +      },
```suggestion
      "ActiveReportID": {
        "Start": 80,
        "StartInclusive": true,
        "End": 96,
        "EndInclusive": false
      },
```

2021-01-22 10:06 UTC, X9VoiD approved these changes

2021-01-22 10:15 UTC, X9VoiD commented
Closes #507

2021-01-26 05:24 UTC, InfinityGhost approved these changes
This configuration lacks any auxiliary support, so will mark as `missing features`

2021-01-26 05:24 UTC, merged