Cache and vectorize WindowsAbsolutePointer's conversion
InfinityGhost/OpenTabletDriver pull request #729
Opened 2021-01-28 13:27 UTC by X9VoiD

**Pre-PR**

![image](https://user-images.githubusercontent.com/10338031/106144649-75e44f80-61af-11eb-9326-6c3552ac86a7.png)

**Post-PR**

![image](https://user-images.githubusercontent.com/10338031/106144529-459cb100-61af-11eb-8180-222ed4ec4157.png)

2021-01-28 13:32 UTC, AbstractQbit commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
We need to either observe screen config changes somehow, or refresh this value periodically

2021-01-28 13:57 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
Screen config changes currently don't trigger in the first place, so this really isn't a big deal right now.

2021-01-28 13:59 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
OTD have no way of detecting resolution changes right now. Periodically refreshing it will require locking and changing `IOutputMode` to implement `IDisposable`, or a periodic timer that OTD will run on start to avoid `IDisposable` output modes.

2021-01-28 13:59 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
```patch
diff --git a/OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs b/OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
index 0f6274b..1754fb9 100644
--- a/OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
+++ b/OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
@@ -9,11 +9,30 @@ namespace OpenTabletDriver.Desktop.Interop.Input.Absolute
 
     public class WindowsAbsolutePointer : WindowsVirtualMouse, IAbsolutePointer
     {
-        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
+        static WindowsAbsolutePointer()
+        {
+            timer = new System.Timers.Timer(250);
+            timer.Elapsed += (_, elapsedArgs) =>
+            {
+                lock (stateLock)
+                {
+                    ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
+                }
+            };
+        }
+
+        private static object stateLock;
+        private static System.Timers.Timer timer;
+        private static Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
 
         public void SetPosition(Vector2 pos)
         {
-            var virtualDesktopCoords = pos / ScreenToVirtualDesktop;
+            Vector2 virtualDesktopCoords;
+            lock (stateLock)
+            {
+                virtualDesktopCoords = pos / ScreenToVirtualDesktop;
+            }
+
             inputs[0].U.mi.dwFlags = MOUSEEVENTF.ABSOLUTE | MOUSEEVENTF.MOVE | MOUSEEVENTF.VIRTUALDESK;
             inputs[0].U.mi.dx = (int)virtualDesktopCoords.X;
             inputs[0].U.mi.dy = (int)virtualDesktopCoords.Y;
```
The simplest we could make it right now without IDisposable or the screen resolution event is this

2021-01-28 14:15 UTC, AbstractQbit commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
> Screen config changes currently don't trigger in the first place

Umm, rn on master it calls `private static List<DisplayInfo> GetDisplays()` on each output operation, in each getter, so it always uses up to date display config. That's the whole reason behind high CPU usage

2021-01-28 14:17 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private Vector2 ScreenToVirtualDesktop = new Vector2(SystemInterop.VirtualScreen.Width, SystemInterop.VirtualScreen.Height) / 65535;
> > Screen config changes currently don't trigger in the first place
> 
> Umm, rn on master it calls `private static List<DisplayInfo> GetDisplays()` on each output operation, in each getter, so it always uses up to date display config. That's the whole reason behind high CPU usage

Thought this was cached, mb

2021-01-29 03:45 UTC, InfinityGhost requested changes
I wonder if the locking might cause input stuttering, would rather avoid that at all costs. Some sort of event hook would be a better way to check the display change instead of just throwing this in a timer.

2021-01-29 03:45 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private static object stateLock;
Don't you need to initialize the object for the lock to work?

2021-01-29 03:45 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +            timer = new System.Timers.Timer(250);
That's quite often to update for something that's unlikely to change often, assuming the unit is ms.

2021-01-29 05:39 UTC, X9VoiD commented
Until an event hook is realized for detecting screen resolution OTD-wide, then we settle with this for now. Just to be sure I tried reading and testing out stuff. Turns out my old knowledge of "getting partially written" is not applicable here, so the lock can be removed.

2021-01-30 15:29 UTC, InfinityGhost requested changes
Looks good, just want one code quality change.

2021-01-30 15:29 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private static System.Timers.Timer timer;
Would prefer `System.Threading.Timer`, and just add a `using` statement instead of the path.

2021-01-30 17:06 UTC, X9VoiD commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private static System.Timers.Timer timer;
![image](https://user-images.githubusercontent.com/10338031/106360633-8f72cc00-6354-11eb-9d96-f7772d16968d.png)

It is confused with which `Timer` is referred to due to `OpenTabletDriver.Desktop.Interop.Timer` namespace

2021-01-30 17:40 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +        private static System.Timers.Timer timer;
Keep it explicit, switch to threading timer.

2021-01-31 22:33 UTC, InfinityGhost approved these changes

2021-01-31 22:33 UTC, InfinityGhost commented on OpenTabletDriver.Desktop/Interop/Input/Absolute/WindowsAbsolutePointer.cs
> +            }, null, TimeSpan.Zero, TimeSpan.FromSeconds(1));
Would like to see this cleaned up, but not gonna be a stickler about it.
```suggestion
            timer = new System.Threading.Timer(
                state => ScreenToVirtualDesktop = new Vector2(
                    SystemInterop.VirtualScreen.Width,
                    SystemInterop.VirtualScreen.Height
                ) / 65535,
                null,
                TimeSpan.Zero,
                TimeSpan.FromSeconds(1)
            );
```

2021-02-01 05:34 UTC, merged