Add Star 06C configuration
InfinityGhost/OpenTabletDriver pull request #764
Opened 2021-02-09 15:37 UTC by X9VoiD

## Verification

[#437 comment](https://github.com/InfinityGhost/OpenTabletDriver/issues/437#issuecomment-775907352)

Fixes #437

2021-02-18 23:46 UTC, InfinityGhost requested changes
Appears like this config doesn't support auxiliary buttons, does this tablet have them?

2021-02-18 23:46 UTC, InfinityGhost commented on OpenTabletDriver/Configurations/XP-Pen/Star 06C.json
> +      "ReportParser": null,
Report parser must be defined explicitly.

2021-02-22 11:28 UTC, X9VoiD commented on OpenTabletDriver/Configurations/XP-Pen/Star 06C.json
> +      "ReportParser": null,
Fixed.

2021-02-23 17:31 UTC, InfinityGhost approved these changes

2021-02-23 17:32 UTC, merged