Fixes InfinityGhost/OpenTabletDriver#700
InfinityGhost/OpenTabletDriver pull request #790
Opened 2021-02-21 07:04 UTC by George-lewis

If the tablet is unplugged while reading data `byte[] report` may be incomplete. Thus we can check its length before processing the report.

2021-02-21 07:23 UTC, X9VoiD requested changes

2021-02-21 07:23 UTC, X9VoiD commented on OpenTabletDriver/Tablet/TabletReport.cs
> +
This only solves it for a single report parser and adds an `if` on a hot path. It doesn't solve the issue for the wacom parsers. Remove this and just catch `ArgumentOutOfRangeException` instead on `DeviceReader.cs`. That way, it'll fix OOR issue on all parsers and avoid a branch on a hot path.

2021-02-21 07:23 UTC, X9VoiD commented on OpenTabletDriver/Devices/DeviceReader.cs
> +            }
```suggestion
            catch (ArgumentOutOfRangeException)
            {
                Log.Write("Device", "Not enough report data returned by the device. Was it disconnected?");
            }
```

2021-02-21 07:41 UTC, X9VoiD approved these changes

2021-02-21 07:41 UTC, George-lewis commented on OpenTabletDriver/Tablet/TabletReport.cs
> +
Thank you for the quick reply. I agree this is much better, now there is no need to proactively throw an exception.

2021-02-21 07:54 UTC, AbstractQbit commented
I'd recommend squashing this pr, this level of detail seems really unnecessary for 4 lines of change.

2021-02-21 08:09 UTC, George-lewis commented
> I'd recommend squashing this pr, this level of detail seems really unnecessary for 4 lines of change.

I think I got it. Look good to you?

2021-02-21 08:12 UTC, AbstractQbit approved these changes

2021-02-22 01:10 UTC, InfinityGhost approved these changes
Always good to have more descriptive messages for these sorts of issues.

2021-02-24 20:19 UTC, merged