Add IntuosV2AuxReport, bump aux buttons to 8, discard idle reports
InfinityGhost/OpenTabletDriver pull request #795
Opened 2021-02-22 17:07 UTC by AbstractQbit

2021-02-23 17:34 UTC, InfinityGhost commented on OpenTabletDriver/Vendors/Wacom/IntuosV3ReportParser.cs
> +                _ => null
This might have potential side effects we're not aware of, do output modes handle null reports?

2021-02-23 17:51 UTC, AbstractQbit commented on OpenTabletDriver/Vendors/Wacom/IntuosV3ReportParser.cs
> +                _ => null
If the report is null it won't be emitted 
https://github.com/InfinityGhost/OpenTabletDriver/blob/55b21bd58c66ca2c46b5c86f42b5c1f0ea4a24ce/OpenTabletDriver/Devices/DeviceReader.cs#L64-L65

2021-02-24 20:37 UTC, InfinityGhost requested changes
One minor change, otherwise this is good.

2021-02-24 20:37 UTC, InfinityGhost commented on OpenTabletDriver/Devices/DeviceReader.cs
> +                    if (report is not null)
```suggestion
                    if (report != null)
```

2021-02-24 20:40 UTC, InfinityGhost approved these changes

2021-02-24 20:41 UTC, merged