Handle Missing Config Directory
InfinityGhost/OpenTabletDriver pull request #797
Opened 2021-02-23 01:25 UTC by George-lewis

I found this bug while investigating a related issue. In my source tree the config directory didn't exist and this code was causing a hard crash. Now, if the directory doesn't exist it's created and `sortedConfigs` is initialized as empty.

Please let me know if there's a more concise way to write this or if some restyling is needed.. I am new to C#

2021-02-23 17:21 UTC, InfinityGhost requested changes

2021-02-23 17:21 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Configurations/ConfigurationEditor.cs
> +                              select Serialization.Deserialize<TabletConfiguration>(file);
```suggestion
                var configs = from file in dir.GetFiles("*.json", SearchOption.AllDirectories)
                    select Serialization.Deserialize<TabletConfiguration>(file);
```

2021-02-23 17:21 UTC, InfinityGhost commented on OpenTabletDriver.UX/Windows/Configurations/ConfigurationEditor.cs
> +            if (dir.Exists)
Depending on where the `dir` variable came from, the `Exists` property isn't always up to date, however in this case it *should* be fairly safe to use. Would be a good idea to add a `dir.Refresh()` call to ensure its up to date.

2021-02-23 17:40 UTC, George-lewis commented on OpenTabletDriver.UX/Windows/Configurations/ConfigurationEditor.cs
> +            if (dir.Exists)
I've added a `.Refresh()` call.

2021-02-24 20:16 UTC, InfinityGhost approved these changes

2021-02-24 23:41 UTC, merged